apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-k8s-crud-example
spec:
  selector:
    matchLabels:
      app: springboot-k8s
  replicas: 3
  template:
    metadata:
      labels:
        app: springboot-k8s
    spec:
      containers:
        - name: springboot-k8s-crud-imagename
          image: springboot-k8-crud
          ports:
            - containerPort: 8083